services:
  db:
    image: mysql:8.0
    container_name: gametracker_db
    restart: always
    environment:
      MYSQL_DATABASE: gametracker
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user_gt
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"  # Port 3307 sur ton PC pour éviter le conflit avec ton autre projet
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: gametracker_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./output:/app/output
    environment:
      - DB_HOST=db
      - DB_PORT=3306  # L'app parle à la DB sur le port interne (toujours 3306)
      - DB_USER=user_gt
      - DB_PASSWORD=user_password
      - DB_NAME=gametracker
    command: tail -f /dev/null
    # Remplace tail -f /dev/null par :
    #command: ["/bin/bash", "./scripts/run_pipeline.sh"]
volumes:
  db_data: